# Generated by Django 5.1.2 on 2024-12-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_options_alter_borrowing_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
