# Generated by Django 5.1.2 on 2024-12-07 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_book_recommended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='recommended',
        ),
    ]
